{
    'name': 'KPT Sale Order Extension',
    'version': '17.0.1.0.1',
    'category': 'Sales',
    'depends': [
        'sale_management',
        'sale',
        'stock',
        'account',
        'purchase',
        'l10n_in_ewaybill_stock',
        'mrp',
        'mrp_account',
        'sale_order_discount_approval_odoo',
    ],
    'data': [
        'security/ir.model.access.csv',
        'wizard/net_purchase_report.xml',
        'wizard/gross_purchase_report.xml',
        'views/sale_order_view.xml',
        'views/delivery_slip_template.xml',
        'views/delivery_challan.xml',
        'views/delivery_note.xml',
        'views/kpt_sale_quotation_template.xml',
        'views/kpt_pro_forma_invoice.xml',
        'views/kpt_purchase_order_template.xml',
        'views/kpt_ewaybill_report.xml',
        'views/stock_picking.xml',
        'reports/qweb_reports.xml',
        'views/pro_forma_dispatch_team.xml',
        'views/kpt_tax_invoice.xml',
        'views/purchase_order.xml',
        'views/account_move.xml',
        'views/mrp.xml',
        'views/net_purchase_template.xml',
        'views/gross_purchase_template.xml',
        'views/product_view.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}
