from . import mastergst_edi
from . import res_config
from . import res_company
from . import account_move
from . import error_codes
from . import initiate_multivehicle
from . import partb
from . import add_multivehicle
from . import change_multivehicle